name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    - run: |
        ls -ila
        docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/dind-alpine-k8s:0.0.1
        docker push ghcr.io/${{ github.actor }}/dind-alpine-k8s:0.0.1
