name: 'Create Docker Image'


on:
  push:
    branches:
      - build
      
env:
  IMAGE_NAME: 'ghcr.io/${{github.repository_owner}}/dind-alpine-k8s'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: ${{github.repository_owner}}
        password: ${{secrets.GITHUB_TOKEN}}
    - run: |
        docker build --no-cache . -f Dockerfile -t ${IMAGE_NAME}:latest
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${GITHUB_SHA::6}

    - run: |
        docker push ${IMAGE_NAME}:${GITHUB_SHA::6}
        docker push ${IMAGE_NAME}:latest
