name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dind-alpine-k8s:$(date +%s)

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    - run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/dind-alpine-k8s:0.0.1
        docker push ghcr.io/${{ github.actor }}/dind-alpine-k8s:0.0.1
